[package]
name = "obsidian_render"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.34"
log = "0.4.11"
raw-window-handle = "0.3.3"

[features]
default = ["vulkan"]
vulkan = []